export const RECEIVE_ADDRESS = 'receive_address'
export const RECEIVE_CATEGORY = 'receive_category'
export const RECEIVE_SHOPS = 'receive_shops'
export const SET_USER_INFO = 'set_user_info'
export const RESET_USER_INFO = 'reset_user_info'
// mock
export const RECEIVE_GOODS = 'receive_goods'
export const RECEIVE_RATINGS = 'receive_ratings'
export const RECEIVE_INFO = 'receive_info'
export const ADD_CART = 'add_cart'
export const SUB_CART = 'sub_cart'
export const CLEAR_CART = 'clear_cart'
